=== AlexeyFor/JavaSt2021/task08/src/main/resources/data/gems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.training.by/entities"
xmlns:mstns="http://www.training.by/entities"
 xmlns:tns="http://www.training.by/entities" elementFormDefault="qualified">

	<element name="gems">
		<complexType>
			<sequence>
				<element ref="tns:gem" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
		  <unique name="UniqueGemKey">
    <selector xpath="mstns:processedGem|mstns:unprocessedGem" /> 
    <field xpath="@ID" /> 
  </unique>
	</element>

	<element name="gem" type="tns:Gem" abstract="true"></element>
	<element name="processedGem" type="tns:ProcessedGem" substitutionGroup="tns:gem"></element>
	<element name="unprocessedGem" type="tns:UnprocessedGem" substitutionGroup="tns:gem"></element>

	<complexType name="Gem">
		<sequence>
			<element name="name">
				<simpleType>
					<restriction base="string">
						<pattern value="[a-zA-Z]{1,30}" />
					</restriction>
				</simpleType>
			</element>
			<element name="price">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0" />
					</restriction>
				</simpleType>
			</element>
			<element name="dateOfReceiving" type="date" />
			<element name="originCountry" type="string" minOccurs="1" default="none" />
			<element name="colour" type="string" />
			<element name="transporancy">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0" />
						<maxInclusive value="100" />
					</restriction>
				</simpleType>
			</element>
			<element name="weight">
				<simpleType>
					<restriction base="decimal">
						<minInclusive value="0" />
					</restriction>
				</simpleType>
			</element>
		</sequence>

		<attribute  name="ID" use="required" type="token" />

		<attribute name="preciousness"  use="optional"  default="notClassified">
			<simpleType>
				<restriction base="string">
					<enumeration value="notClassified"></enumeration>
					<enumeration value="precious"></enumeration>
					<enumeration value="half-precious"></enumeration>
				</restriction>
			</simpleType>
		</attribute>

	</complexType>


	<complexType name="ProcessedGem">
		<complexContent>
			<extension base="tns:Gem">
				<sequence>
					<element name="processedType">
						<simpleType>
							<restriction base="string">
								<enumeration value="manual"></enumeration>
								<enumeration value="half-manual"></enumeration>
								<enumeration value="automatic"></enumeration>
							</restriction>
						</simpleType>
					</element>
					<element name="facesNumber">
						<simpleType>
							<restriction base="int">
								<minInclusive value="4" />
								<maxInclusive value="15" />
							</restriction>
						</simpleType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="UnprocessedGem">
		<complexContent>
			<extension base="tns:Gem">
				<sequence>
					<element name="height" type="decimal" />
					<element name="length" type="decimal" />
					<element name="width" type="decimal" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>


</schema>

=== AlexeyFor/JavaSt2021/task08/src/main/resources/data/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.training.by/entities" xsi:schemaLocation="http://www.training.by/entities  gems.xsd">

	<unprocessedGem ID="1000001" preciousness="precious">
		<name>diamond</name>
		<price>2500</price>
		<dateOfReceiving>2020-05-05</dateOfReceiving>
		<originCountry>Nigeria</originCountry>
		<colour>white</colour>
		<transporancy>56</transporancy>
		<weight>56.0</weight>
		<height>11.0</height>
		<length>5.0</length>
		<width>7.0</width>
	</unprocessedGem>

	<processedGem ID="1000002" preciousness="precious">
		<name>diamond</name>
		<price>4045</price>
		<dateOfReceiving>2020-02-28</dateOfReceiving>
		<originCountry></originCountry>
		<colour>white</colour>
		<transporancy>87</transporancy>
		<weight>16.0</weight>
		<processedType>manual</processedType>
		<facesNumber>14</facesNumber>
	</processedGem>
	
	<processedGem  preciousness="precious" ID="1000003">
		<name>ruby</name>
		<price>400</price>
		<dateOfReceiving>2015-03-03</dateOfReceiving>
		<originCountry></originCountry>
		<colour>red</colour>
		<transporancy>43</transporancy>
		<weight>2.3</weight>
		<processedType>half-manual</processedType>
		<facesNumber>6</facesNumber>
	</processedGem>

	
		<unprocessedGem ID="1000004" >
		<name>emerald</name>
		<price>4000</price>
		<dateOfReceiving>2014-03-03</dateOfReceiving>
		<originCountry>Nikaragua</originCountry>
		<colour>green</colour>
		<transporancy>37</transporancy>
		<weight>2.4</weight>
		<height>13.0</height>
		<length>5.2</length>
		<width>7.1</width>
	</unprocessedGem>
	
	<processedGem ID="1000005" >
		<name>saphire</name>
		<price>13000</price>
		<dateOfReceiving>2012-03-03</dateOfReceiving>
		<originCountry></originCountry>
		<colour>red</colour>
		<transporancy>43</transporancy>
		<weight>2.3</weight>
		<processedType>manual</processedType>
		<facesNumber>9</facesNumber>
	</processedGem>
	
	<unprocessedGem ID="1000006" preciousness="precious">
		<name>pearl</name>
		<price>1300</price>
		<dateOfReceiving>2012-07-06</dateOfReceiving>
		<originCountry>Cuba</originCountry>
		<colour>white</colour>
		<transporancy>100</transporancy>
		<weight>5.7</weight>
		<height>4.0</height>
		<length>4.0</length>
		<width>4.0</width>
	</unprocessedGem>

<unprocessedGem ID="1000007" preciousness="half-precious">
		<name>amethyst</name>
		<price>30</price>
		<dateOfReceiving>2012-03-06</dateOfReceiving>
		<originCountry>Brazil</originCountry>
		<colour>violet</colour>
		<transporancy>37</transporancy>
		<weight>7.4</weight>
		<height>12.0</height>
		<length>5.4</length>
		<width>7.3</width>
	</unprocessedGem>


<unprocessedGem ID="1000008" preciousness="half-precious">
		<name>chrysolite</name>
		<price>37</price>
		<dateOfReceiving>2012-11-06</dateOfReceiving>
		<originCountry></originCountry>
		<colour>golden</colour>
		<transporancy>50</transporancy>
		<weight>7.1</weight>
		<height>6.0</height>
		<length>5.4</length>
		<width>2.3</width>
	</unprocessedGem>
	
	
<processedGem ID="1000009" >
		<name>garnet</name>
		<price>500</price>
		<dateOfReceiving>2008-04-09</dateOfReceiving>
		<originCountry>India</originCountry>
		<colour>red</colour>
		<transporancy>53</transporancy>
		<weight>10.6</weight>
		<processedType>half-manual</processedType>
		<facesNumber>11</facesNumber>
	</processedGem>

<processedGem ID="1000010" >
		<name>garnet</name>
		<price>500</price>
		<dateOfReceiving>2008-04-09</dateOfReceiving>
		<originCountry>Gvatemalla</originCountry>
		<colour>red</colour>
		<transporancy>53</transporancy>
		<weight>10.6</weight>
		<processedType>half-manual</processedType>
		<facesNumber>11</facesNumber>
	</processedGem>

<processedGem ID="1000011" preciousness="half-precious">
		<name>topaz</name>
		<price>25</price>
		<dateOfReceiving>2020-05-07</dateOfReceiving>
		<originCountry></originCountry>
		<colour>red</colour>
		<transporancy>53</transporancy>
		<weight>10.6</weight>
		<processedType>automatic</processedType>
		<facesNumber>15</facesNumber>
	</processedGem>


</gems>
